import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import vm from 'node:vm';
import { createServer } from '../scripts/serve.mjs';
const require = createRequire(import.meta.url);
let chromium;
try { ({ chromium } = require('playwright')); }
catch { ({ chromium } = require(process.env.PRIVATEPDF_RUNTIME_MODULES + '/playwright')); }
await mkdir('test-results', { recursive: true });
vm.runInThisContext(await readFile(new URL('../src/vendor/pdf-lib/dist/pdf-lib.min.js', import.meta.url), 'utf8'));
const doc = await PDFLib.PDFDocument.create(); doc.addPage().drawText('CONFIDENTIAL ACCOUNT DOCUMENT');
await writeFile('test-results/account-input.pdf', await doc.save());
const server = createServer({ databasePath: ':memory:' });
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const url = `http://127.0.0.1:${server.address().port}`;
let browser;
try {
    browser = await chromium.launch({ headless: true, channel: process.env.PRIVATEPDF_BROWSER_CHANNEL || 'msedge' });
    const context = await browser.newContext({ viewport: { width: 1360, height: 1000 }, acceptDownloads: true });
    const page = await context.newPage(), errors = [], external = [], activities = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => {
        if (/^https?:/.test(request.url()) && !request.url().startsWith(url)) external.push(request.url());
        if (request.url().endsWith('/api/activity') && request.method() === 'POST') activities.push(JSON.parse(request.postData()));
    });
    await page.goto(url + '/dashboard.html'); await page.waitForURL('**/account.html');
    await page.locator('#account-switch').click();
    await page.locator('#register-fields').waitFor({ state: 'visible' });
    await page.screenshot({ path: 'test-results/register-desktop.png', fullPage: true });
    await page.locator('#account-name').fill('Alice'); await page.locator('#account-email').fill('alice@example.test');
    await page.locator('#account-password').fill('una password lunga e privata'); await page.locator('#confirm-password').fill('different password');
    await page.locator('#submit-account').click(); assert.match(await page.locator('#account-status').textContent(), /non coincidono/);
    await page.locator('#confirm-password').fill('una password lunga e privata'); await page.locator('#submit-account').click();
    await page.waitForURL('**/dashboard.html'); await page.locator('#dashboard-content').waitFor({ state: 'visible' });
    assert.equal(await page.locator('#greeting').textContent(), 'Ciao, Alice.');
    assert.equal(await page.locator('#total-operations').textContent(), '0');
    assert.ok((await context.cookies()).find(cookie => cookie.name === 'privatepdf_session')?.httpOnly);
    assert.equal(await page.evaluate(() => localStorage.length), 0);
    await page.reload(); await page.locator('#dashboard-content').waitFor({ state: 'visible' });
    await page.locator('a.tool-link').click();
    await page.locator('#account-nav').getByRole('link', { name: 'Dashboard', exact: true }).waitFor();
    await page.locator('#file-input').setInputFiles({ name: 'secret-contract.pdf', mimeType: 'application/pdf', buffer: await readFile('test-results/account-input.pdf') });
    await page.waitForFunction(() => document.getElementById('status').textContent.startsWith('File pronti'));
    const recorded = page.waitForResponse(response => response.url().endsWith('/api/activity') && response.status() === 201);
    const downloaded = page.waitForEvent('download');
    await page.locator('[data-operation="metadata"]').click(); await downloaded; await recorded;
    assert.deepEqual(activities, [{ operation: 'metadata' }]);
    await page.locator('#account-nav').getByRole('link', { name: 'Dashboard', exact: true }).click();
    await page.locator('#dashboard-content').waitFor({ state: 'visible' });
    assert.equal(await page.locator('#total-operations').textContent(), '1');
    assert.match(await page.locator('#activity-list').textContent(), /Pulizia metadati/);
    assert.equal((await page.locator('#activity-list').textContent()).includes('secret-contract.pdf'), false);
    await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.locator('#profile-name').fill('Alice aggiornata'); await page.locator('#save-profile').click();
    await page.waitForFunction(() => document.getElementById('greeting').textContent.includes('aggiornata'));
    await page.locator('#clear-history').click(); await page.locator('#confirm-clear').click();
    await page.waitForFunction(() => document.getElementById('total-operations').textContent === '0');
    await page.locator('#profile details summary').click();
    await page.locator('#current-password').fill('una password lunga e privata');
    await page.locator('#new-password').fill('nuova password privata e lunga'); await page.locator('#new-password-confirm').fill('nuova password privata e lunga');
    await page.locator('#save-password').click(); await page.waitForURL('**/account.html?passwordChanged=1');
    await page.locator('#account-email').fill('alice@example.test'); await page.locator('#account-password').fill('wrong-password');
    await page.locator('#submit-account').click(); await page.waitForFunction(() => document.getElementById('account-status').textContent.includes('non corretti'));
    await page.locator('#account-password').fill('nuova password privata e lunga'); await page.locator('#submit-account').click();
    await page.waitForURL('**/dashboard.html'); await page.locator('#dashboard-content').waitFor({ state: 'visible' });
    await page.locator('#logout').click(); await page.waitForURL(url + '/');
    await page.locator('#account-nav').getByRole('link', { name: 'Accedi', exact: true }).waitFor();
    await page.goto(url + '/account.html?mode=register'); await page.locator('#register-fields').waitFor({ state: 'visible' });
    await page.screenshot({ path: 'test-results/register-mobile.png', fullPage: true });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    assert.deepEqual(errors, []); assert.deepEqual(external, []);
    console.log('Account browser checks passed: register, login, reload, dashboard, PDF activity without filenames, profile, clear history, password change, logout, mobile.');
} finally { if (browser) await browser.close(); await new Promise(resolve => server.close(resolve)); }
