import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import vm from 'node:vm';
import { createServer } from '../scripts/serve.mjs';
const require = createRequire(import.meta.url);
let chromium;
try { ({ chromium } = require('playwright')); }
catch { ({ chromium } = require(process.env.PRIVATEPDF_RUNTIME_MODULES + '/playwright')); }
vm.runInThisContext(await readFile(new URL('../src/vendor/pdf-lib/dist/pdf-lib.min.js', import.meta.url), 'utf8'));
await mkdir('test-results', { recursive: true });
const fixture = await PDFLib.PDFDocument.create();
fixture.addPage([600, 800]).drawText('PRIVATE DOCUMENT SECRET', { x: 50, y: 700, size: 26 });
fixture.addPage([500, 700]).drawText('SECOND PAGE', { x: 50, y: 600, size: 26 });
fixture.setAuthor('Private author');
await writeFile('test-results/input.pdf', await fixture.save());
const scan = await PDFLib.PDFDocument.create();
scan.addPage([600, 400]).drawText('PRIVATE DOCUMENT', { x: 45, y: 200, size: 38 });
await writeFile('test-results/ocr-input.pdf', await scan.save());
const server = createServer();
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const url = `http://127.0.0.1:${server.address().port}`;
let browser;
try {
    browser = await chromium.launch({ headless: true, channel: process.env.PRIVATEPDF_BROWSER_CHANNEL || 'msedge' });
    const page = await browser.newPage({ viewport: { width: 1280, height: 900 }, acceptDownloads: true });
    const errors = [], external = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => { if (/^https?:/.test(request.url()) && !request.url().startsWith(url)) external.push(request.url()); });
    await page.goto(url);
    await page.screenshot({ path: 'test-results/home.png', fullPage: true });
    await page.locator('#file-input').setInputFiles('test-results/input.pdf');
    await page.waitForFunction(() => document.getElementById('status').textContent.startsWith('File pronti'));
    assert.equal(await page.locator('.page-grid-item').count(), 2);
    await page.screenshot({ path: 'test-results/workspace.png', fullPage: true });
    async function download(selector, name) {
        const pending = page.waitForEvent('download');
        await page.locator(selector).click();
        const result = await pending; await result.saveAs(`test-results/${name}`);
        await page.waitForFunction(() => document.getElementById('workspace').getAttribute('aria-busy') === 'false');
        assert.equal(await result.failure(), null);
        return new Uint8Array(await readFile(`test-results/${name}`));
    }
    const metadata = await download('[data-operation="metadata"]', 'metadata.pdf');
    assert.equal((await PDFLib.PDFDocument.load(metadata, { updateMetadata: false })).getAuthor(), undefined);
    await page.locator('#delete-pages').fill('1abc');
    await page.locator('#btn-delete').click();
    await page.waitForFunction(() => document.getElementById('status').classList.contains('error'));
    await page.locator('#delete-pages').fill('1,1');
    assert.equal((await PDFLib.PDFDocument.load(await download('#btn-delete', 'deleted.pdf'))).getPageCount(), 1);
    await page.locator('#reorder-pages').fill('2,1');
    assert.equal((await PDFLib.PDFDocument.load(await download('#btn-reorder', 'reordered.pdf'))).getPage(0).getWidth(), 500);
    await page.locator('#duplicate-pages').fill('1,1,2');
    assert.equal((await PDFLib.PDFDocument.load(await download('#btn-duplicate', 'duplicate.pdf'))).getPageCount(), 3);
    await download('#btn-extract', 'extract.pdf');
    await download('#btn-split', 'split.zip');
    await download('[data-operation="watermark"]', 'watermark.pdf');
    await download('[data-operation="numbers"]', 'numbers.pdf');
    await page.locator('#output-password').fill('correct-password');
    const encrypted = await download('[data-operation="protect"]', 'protected.pdf');
    await assert.rejects(PDFLib.PDFDocument.load(encrypted, { password: 'wrong' }));
    assert.equal((await PDFLib.PDFDocument.load(encrypted, { password: 'correct-password' })).getPageCount(), 2);
    await page.locator('#btn-clear').click();
    await page.waitForFunction(() => document.getElementById('queue-panel').hidden);
    await page.locator('.password-details summary').click();
    await page.locator('#open-password').fill('correct-password');
    await page.locator('#file-input').setInputFiles('test-results/protected.pdf');
    await page.waitForFunction(() => document.getElementById('status').textContent.startsWith('File pronti'));
    assert.equal((await PDFLib.PDFDocument.load(await download('[data-operation="unlock"]', 'unlocked.pdf'))).getPageCount(), 2);
    await download('#btn-pdf-images', 'images.zip');
    await page.locator('#btn-redact-open').click();
    await page.waitForFunction(() => document.getElementById('workspace').getAttribute('aria-busy') === 'false');
    await page.locator('#redaction-canvas').scrollIntoViewIfNeeded();
    const rect = await page.locator('#redaction-canvas').boundingBox();
    await page.mouse.move(rect.x + rect.width * .05, rect.y + rect.height * .06);
    await page.mouse.down(); await page.mouse.move(rect.x + rect.width * .95, rect.y + rect.height * .22); await page.mouse.up();
    assert.match(await page.locator('#redaction-count').textContent(), /1 aree/);
    await page.screenshot({ path: 'test-results/redaction.png', fullPage: true });
    await download('#btn-redact-save', 'redacted.pdf');
    // Inspect redaction with an independent renderer in browser, using the downloaded bytes.
    const redactedText = await page.evaluate(async bytes => {
        const pdf = await pdfjsLib.getDocument({ data: new Uint8Array(bytes) }).promise;
        let text = ''; for (let i = 1; i <= pdf.numPages; i++) text += (await (await pdf.getPage(i)).getTextContent()).items.map(item => item.str).join(' ');
        await pdf.destroy(); return text;
    }, [...await readFile('test-results/redacted.pdf')]);
    assert.equal(redactedText, '');
    const redactedPixel = await page.evaluate(async bytes => {
        const pdf = await pdfjsLib.getDocument({ data: new Uint8Array(bytes) }).promise;
        const page = await pdf.getPage(1), viewport = page.getViewport({ scale: 1 });
        const canvas = document.createElement('canvas'); canvas.width = viewport.width; canvas.height = viewport.height;
        const context = canvas.getContext('2d'); await page.render({ canvasContext: context, viewport }).promise;
        const pixel = [...context.getImageData(canvas.width * .5, canvas.height * .12, 1, 1).data];
        await pdf.destroy(); return pixel;
    }, [...await readFile('test-results/redacted.pdf')]);
    assert.deepEqual(redactedPixel, [0,0,0,255]);
    await page.locator('#btn-clear').click();
    await page.waitForFunction(() => document.getElementById('queue-panel').hidden);
    await page.locator('#file-input').setInputFiles(['test-results/input.pdf', 'test-results/ocr-input.pdf']);
    await page.waitForFunction(() => document.getElementById('status').textContent.startsWith('File pronti'));
    assert.equal((await PDFLib.PDFDocument.load(await download('#btn-merge', 'merged.pdf'))).getPageCount(), 3);
    await page.locator('#queue-panel details summary').click();
    await download('#btn-batch', 'batch.zip');
    await page.locator('.file-name-button').filter({ hasText: 'ocr-input.pdf' }).click();
    await page.waitForFunction(() => document.getElementById('workspace').getAttribute('aria-busy') === 'false');
    await page.locator('#ocr-language').selectOption('eng');
    await download('#btn-ocr', 'ocr.zip');
    await page.locator('#btn-clear').click();
    await page.waitForFunction(() => document.getElementById('queue-panel').hidden);
    const png = await page.evaluate(() => {
        const canvas = document.createElement('canvas'); canvas.width = canvas.height = 1200;
        const context = canvas.getContext('2d'), pixels = context.createImageData(1200,1200);
        for (let i = 0; i < pixels.data.length; i += 4) { pixels.data[i] = (i * 7) % 251; pixels.data[i+1] = (i * 13) % 241; pixels.data[i+2] = (i * 19) % 239; pixels.data[i+3] = 255; }
        context.putImageData(pixels,0,0); return canvas.toDataURL('image/png').split(',')[1];
    });
    await writeFile('test-results/image.png', Buffer.from(png, 'base64'));
    await page.locator('#file-input').setInputFiles('test-results/image.png');
    await page.waitForFunction(() => document.getElementById('status').textContent.startsWith('File pronti'));
    const imagePdf = await download('#btn-images-to-pdf', 'image.pdf');
    assert.equal((await PDFLib.PDFDocument.load(imagePdf)).getPageCount(), 1);
    await page.locator('#file-input').setInputFiles('test-results/image.pdf');
    await page.waitForFunction(() => document.getElementById('status').textContent.startsWith('File pronti'));
    const optimized = await download('[data-operation="compress"]', 'optimized.pdf');
    assert.ok(optimized.length <= imagePdf.length);
    await page.locator('#compression-mode').selectOption('raster');
    const lossy = await download('[data-operation="compress"]', 'compressed.pdf');
    assert.ok(lossy.length < imagePdf.length);
    await page.locator('#file-input').setInputFiles({ name: 'broken.pdf', mimeType: 'application/pdf', buffer: Buffer.from('not a PDF') });
    await page.waitForFunction(() => document.getElementById('status').classList.contains('error'));
    assert.equal(await page.locator('#file-list-ui li').count(), 2);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    assert.deepEqual(external, []); assert.deepEqual(errors, []);
    console.log('Browser flows passed: metadata, page operations, encryption, unlock, PNG, redaction, merge, batch, real OCR, mobile, no external requests.');
} finally { if (browser) await browser.close(); await new Promise(resolve => server.close(resolve)); }
